### ISSUE TITLE
Auto-(re)connect/bind on connection network errors

### ISSUE THREAD

**Issue by emsearcy** [go-ldap/ldap#197] opened 2018-11-26 18:07 UTC
As an alternative to #47, I think it would be useful for long-running services if there was a feature for the LDAP connection to attempt to re-connect/bind on connection errors, similar to how database/sql  maintains connections.

However, unlike database/sql and #47, I don't think that LDAP actually needs pooling, because one LDAP connection can handle multiple asynchronous requests.

**Comment by cstarke** [comment] 2018-12-12 15:15
Could that be a duplicate of https://github.com/go-ldap/ldap/issues/181 ? :)

**Comment by emsearcy** [comment] 2018-12-12 16:35
They look slightly different. In my case, the LDAP server is terminated an idle connection (not a TCP timeout), and a bind is success.  In #181, the bind does not success.

**Comment by cstarke** [comment] 2018-12-12 16:36
Ah, indeed! :)

**Comment by Arttii** [comment] 2018-12-14 16:47
We also are having an issue with this, does anyone have a workaround perhaps?

**Comment by emsearcy** [comment] 2018-12-14 17:17
As a workaround, you can put your LDAP search/modify/etc in a loop (I'm using a max-retry counter to avoid an infinite loop), and escape out of the loop on success, on a non-network error. on a network error, attempt to re-bind (I also escape out of the loop if this happens) and loop.

I think binding may not be concurrency-safe, so you have to protect that appropriately.

(Oh, and to test for a network error, use ldap.IsErrorWithCode(err, 200))

**Comment by pkoutsovasilis** [comment] 2019-12-29 10:18
I respectfully don't agree with either the enhancement proposal or the workaround :). First please let me put this here from the official ldapv3 [oracle documentation](https://docs.oracle.com/javase/jndi/tutorial/ldap/models/v3.html) documentation. 

> The "bind" operation is optional and can be sent multiple times during a session. If a client requests an operation to be performed without doing an explicit bind, the client is treated as "anonymous." The client can also send a "bind" operation in the middle of a session to change the client's credentials (without sending an unbind first).

So I guess the myth of you can't use another bind after a bind is busted, although I wouldn't be surprised if there is a ldap config option which the ldap admin(s) forgot to enable, and thus this is not doable (I am far from ldap expert :) ). Also, an equivalent python ldap library provides such features as ["rebind"](https://ldap3.readthedocs.io/bind.html) but for the shake of being politically correct, there is no such thing as "rebind", it is just a bind operation.

The pooling of connections is beneficial for many reasons, I won't dive into details but the killer reason I think of is the extremely dangerous number of time_wait connections that may end up in your server if there is a spike of requests that you have to do ldap operations.

My 2 cents :)

**Comment by vertoforce** [comment] 2020-05-15 23:57
Hey folks thanks for the discussion on this.  I'm facing a similar issue on a long running connection.  I'd like to simply check if we are no longer connected and re-connect / re-bind if so.  Is there some way to check if the ldap connection is still connected and live?

Otherwise I'll just do it every min 5 minutes.

**Comment by stefanmcshane** [comment] 2021-04-02 19:50
Hi @vertoforce,

Would something like this work?
https://github.com/go-ldap/ldap/issues/33#issuecomment-578531872

I appreciate that it's been a while with no response, so if you came up with another way to solve your issue, please do share!

Thanks,
Stefan

**Comment by clake1-godaddy** [comment] 2021-04-05 17:59
Thanks for the response!  Looking at my code it looks like I did a workaround by just reconnecting if we haven't reconnected in the last 1 minute.  This setup is way better, thanks for sharing :)

**Comment by vertoforce** [comment] 2021-04-05 18:00
Thanks for the response! Looking at my code it looks like I did a workaround by just reconnecting if we haven't reconnected in the last 1 minute. This setup is way better, thanks for sharing :)

**Comment by emsearcy** [comment] 2021-04-05 19:04
For what it's worth, here's an example of the connection code I have ... I realize this is pretty messy but maybe it will be useful to someone: https://gist.github.com/emsearcy/cba3295d1a06d4c432ab4f6173b65e4f (sorry, indentation also was messed-up with a lot of selective copy-pasting and I didn't take time to fix, and there may be references to code not included in the paste)

in this example I have two connections, defined globally. one is used to make read/write administrative calls (rwConn), and the other connection does nothing but one one bind after another to check user passwords (authConn). there is a loop with a select on two nonbuffered channels; one which sends out the current connection, the other receiving reconnection requests. So, if the connection is reconnecting, it blocks code needing a client until the connection attempt has finished (with an error or success). messages to reconnect are non-blocking, so we don't stack reconnection requests.

I've included two example client functions, one for a NewAddRequest on rwConn, and the other for NewSimpleBindRequest on authConn.  This code has been running in prod for 2+ years with high concurrency.  Unlike the example code from #33, this one has no race conditions.

p.s. - @pkoutsovasilis I don't believe I ever said you couldn't bind additional times on the same connection. In fact my code does exactly that (concurrently -- it can send a second bind request "message" on the current connection before the response from the first bind request has completed -- whether this works may be dependent on the LDAP _server_ implementation, though!). And lots of time_wait connections would be the result of making a new connection every request. My "proposal" wouldn't result in lots of time_wait connections. A conventional pool relies on protecting each connection so that it isn't used concurrently. LDAP doesn't need that -- a single connection stored globally can be used concurrently by several goroutines. The challenge when using a single connection concurrently is how to "lock" around your reconnections, and, (if you need to bind) protecting that connection in the critical code section between dial and bind, before any concurrent client code can fetch and use the connection.

**Closed** 2021-11-17 20:39 UTC

**Comment by bgsjanardana** [comment] 2024-05-20 12:43
> As a workaround, you can put your LDAP search/modify/etc in a loop (I'm using a max-retry counter to avoid an infinite loop), and escape out of the loop on success or on a non-network error. On a network error, you can attempt to re-bind (I also escape out of the loop if there is an error at this point) and then loop to retry your search/modify/etc.
> 
> I think binding may not be concurrency-safe, so you have to protect that appropriately.
> 
> Oh, and to test for a network error, use `ldap.IsErrorWithCode(err, 200)`.

Thank you, i found this simple answer. Im literally confused, because my connection to LDAP always get 200 network error sometimes.
