### ISSUE TITLE
Using pagination with pageSize=0 returns 0 records

### ISSUE THREAD

**Issue by jonathanvila** [go-ldap/ldap#379] opened 2022-06-08 14:18 UTC
I'm using SearchWithPagination with a PageSize of 0 , as it is said in the [documentation](https://pkg.go.dev/gopkg.in/ldap.v3#Conn.SearchWithPaging)

```
A requested pagingSize of 0 is interpreted as no limit by LDAP servers.
```

But the result is always 0 rows.

If I set conn.Debug=true then I see 
```error running search query "(objectClass=person)": LDAP Result Code 203 "Debugging Error": ldap: cannot process packet to add descr```

Specifying a value higher than 0 seems to work fine with no issues.

**Comment by cpuschma** [comment] 2022-06-11 14:37
I couldn't reproduce the error running a paging search request against an Active Directory server:
```go
func main() {
	conn, err := ldap.Dial("tcp", "192.168.1.1:389")
	if err != nil {
		log.Fatalln(err)
	}

	conn.Bind("administrator@pusch.local", "robin123!")
	searchResult, err := conn.Search(&ldap.SearchRequest{
		BaseDN:       "DC=pusch,DC=local",
		Scope:        ldap.ScopeWholeSubtree,
		DerefAliases: ldap.NeverDerefAliases,
		SizeLimit:    0,
		Filter:       "(objectClass=*)",
		Controls: []ldap.Control{
			ldap.NewControlPaging(0),
		},
	})
	if err != nil {
		log.Fatalln(err)
	}

	fmt.Println(searchResult)
}
```

Can you share some of your code and the go-ldap version you're using?

**Comment by cpuschma** [comment] 2022-06-11 15:13
OK I managed to reproduce this. It seems that this is an implementation mistake from MS. I ran a paged search request with pageSize = 0 against both an Active Directory and a OpenLDAP server.

The OpenLDAP Server had the necessary page control and the cookie for the client to use for the next request (to request the next batch of entries).
![image](https://user-images.githubusercontent.com/16116826/173193451-33f824c6-49c6-49cd-b40b-66b991e36ac5.png)

The Active Directory server also responded with the paging control in it's response, but the cookie was empty. The LDAP client therefore aborted the paging request, as this matches the behaviour when all results have been fetched.
> The cookie MUST be set to an empty value if there are no more entries to return (i.e., the page of search results returned was the last), or, if there are more entries to return, to an octet string of the server's choosing,used to resume the search.

![image](https://user-images.githubusercontent.com/16116826/173193469-124963e9-bcba-44a9-a166-518fea875af0.png)

I'll dig around a bit more later, but for now this looks like a implementation mistake from Microsoft.

**Comment by cpuschma** [comment] 2022-06-11 15:16
OK I managed to reproduce this. It seems that this is an implementation mistake from MS. I ran a paged search request with pageSize = 0 against both an Active Directory and a OpenLDAP server.

The OpenLDAP Server had the necessary page control and the cookie for the client to use for the next request (to request the next batch of entries).
![image](https://user-images.githubusercontent.com/16116826/173193733-6e7b6647-cbf4-426b-8cfc-af4b994b135c.png)

The Active Directory server also responded with the paging control in it's response, but the cookie was empty. The LDAP client therefore aborted the paging request, as this matches the behaviour when all results have been fetched.
![image](https://user-images.githubusercontent.com/16116826/173193713-b868bab0-0dd8-4b67-8a63-ce660c5728ff.png)

> The cookie MUST be set to an empty value if there are no more entries to return (i.e., the page of search results returned was the last), or, if there are more entries to return, to an octet string of the server's choosing,used to resume the search.

image

I'll dig around a bit more later, but for now this looks like a implementation mistake from Microsoft.

**Comment by cpuschma** [comment] 2022-06-27 20:29
I tried this with different Active Directory server on different domain levels. All answered in the same behaviour unfortunately. I suggest you use the maximum number of allowed results configured for your domain (which should be 10.000 by default)

**Comment by cpuschma** [comment] 2024-04-06 20:48
See #499
Function has been marked as deprecated and will be removed/made private in future releases.

**Closed by cpuschma** 2024-04-06 20:48 UTC
