### ISSUE TITLE
Filter compile fails on empty filter

### ISSUE THREAD

**Issue by Nictec** [go-ldap/ldap#328] opened 2021-07-08 11:04 UTC
The LDAP Search fails if no filter is specified in NewSearch() like in the following code example:
```go
userSearchRequest := ldap3.NewSearchRequest(
		userdn,
		ldap3.ScopeBaseObject,
		ldap3.NeverDerefAliases,
		0, 15,
		false,
		"()",
		[]string{config["email"], config["name"], config["groups"]},
		nil,
	)
```

**Comment by xNevo** [comment] 2021-08-14 23:50
Duplicate of #294

**Comment by johnweldon** [comment] 2021-08-15 02:32
Use `(objectclass=*)`

**Closed by johnweldon** 2021-08-15 02:32 UTC
