### ISSUE TITLE
2017/05/22 14:44:19 LDAP Result Code 200 "": ldap: connection closed error

### ISSUE THREAD

**Issue by rjboer** [go-ldap/ldap#113] opened 2017-05-22 16:46 UTC
when separating the search and bind in separate functions, a connection returned as the type *ldap.Conn cannot be used in other functions. 

The search function (searchrequest2) can be called from the bindldap function which than works...but called from main...it fails...

```
func Bindldap(ldaphost string, port int, principal string, password string) *ldap.Conn {

	l, err := ldap.Dial("tcp", fmt.Sprintf("%s:%d", ldaphost, port))
	if err != nil {
		println("error dialing")
		log.Fatal(err)
	}


	err = l.Bind(principal, password)
	if err != nil {
		println("error binding")
		log.Fatal(err)

	}
	searchrequest2(l)
	println("separator##########################################################################")
	searchrequest2(l)
	return l
}

func searchrequest2(l *ldap.Conn) {
	searchrequest2 := ldap.NewSearchRequest(
		Searchbase1, // The base dn to search
		ldap.ScopeWholeSubtree, ldap.NeverDerefAliases, 0, 0, false,
		"(&(objectClass=organizationalPerson))", // The filter to apply
		Searchattributes2,                       // A list attributes to retrieve
		nil,
	)
	sr, err := l.Search(searchrequest2)
	if err != nil {
		log.Fatal(err)
	}
	for _, entry := range sr.Entries {
		fmt.Printf("%s: %v, %v\n", entry.DN, entry.GetAttributeValue("cn"), entry.GetAttributeValue("sAMAcountName"))
	}
}

func main() {
	println("bind ldap1")
	A := Bindldap(Ldap1, Lport1, Prpl1, Pass1)
	println("#######################################################################3seperator")
	searchrequest2(A)
	A.Close()
}
```

The third search of the same function (triggered from func main) will yield:
2017/05/22 14:44:19 LDAP Result Code 200 "": ldap: connection closed error
wich is really weird

**Comment by vetinari** [comment] 2017-06-29 11:42
because you close it with `defer l.Close()` when the func exits

**Comment by ArtursL** [comment] 2017-10-30 17:24
I just encountered the problem @Virtual-Machine described.

The LDAP server closes the connection after a period of inactivity. The `reader()` goroutine in `ldap.v2/conn.go` notices this and calls `l.Close()`. However, there seems to be no way to check if this has happened, so my only option is to catch the error, reconnect and retry the request.

**Comment by xikunyang** [comment] 2018-10-27 04:11
Could go-ldap export 'isClosing' or auto reconnect?

**Comment by johnweldon** [comment] 2018-10-28 22:49
@xikunyang see discussion on #96

**Closed by johnweldon** 2018-10-28 22:49 UTC

**Comment by L11R** [comment] 2020-01-20 13:29
@andriisoldatenko I reproduce and debug an error by sending conn.Close() in debugger `Evaluate expression...` feature:
![изображение](https://user-images.githubusercontent.com/5345489/72730150-d0f96480-3ba1-11ea-9e9b-07650f0d6530.png)
Dirty, but I didn't find better solution:
```go
func (a *adapter) reconnect() error {
	// Make sure old connection if definitely closed
	a.conn.Close()

	l, err := ldap.DialURL(a.config.URL.String())
	if err != nil {
		return err
	}
	if err := l.StartTLS(&tls.Config{InsecureSkipVerify: true}); err != nil {
		return err
	}
	if err := l.Bind(a.config.Username, a.config.Password); err != nil {
		return err
	}

	a.conn = l
	return nil
}

// And this block somewhere in code
searchResult, err := a.conn.Search(searchRequest)
// Try again if connection closed
if err != nil && ldap.IsErrorWithCode(err, 200) {
	a.logger.WithError(err).Info("Connection is closed, trying to reconnect...")
	if err := a.reconnect(); err != nil {
		a.logger.WithField("username", username).WithError(err).Error("Error while trying to reconnect!")
		return nil, domain.ErrInternalPhotoStorage
	}

	return a.GetPhotoByUsername(username)
} else if err != nil {
	a.logger.WithField("username", username).WithError(err).Error("Error while searching!")
	return nil, domain.ErrInternalPhotoStorage
}
```
